#!/bin/bash
set -e

echo "🌐 [1/3] Building Codespace URLs..."

# Debug: Check environment variables
echo "   DEBUG: CODESPACES=${CODESPACES:-not set}"
echo "   DEBUG: CODESPACE_NAME=${CODESPACE_NAME:-not set}"
echo "   DEBUG: GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN=${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN:-not set}"

# Auto-detect Codespaces environment
if [ -n "$GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN" ]; then
  # In Codespaces, use the forwarding domain
  IS_CODESPACE=true
  # Extract codespace name from the domain or use CODESPACE_NAME if available
  if [ -n "$CODESPACE_NAME" ]; then
    DETECTED_NAME="$CODESPACE_NAME"
  else
    # Try to extract from current hostname or use a fallback
    DETECTED_NAME=$(hostname)
  fi
  echo "   Detected Codespaces environment"
  echo "   Forwarding domain: $GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN"
  echo "   Codespace name: $DETECTED_NAME"
elif [ "$CODESPACES" = "true" ] && [ -n "$CODESPACE_NAME" ]; then
  # Fallback to CODESPACES env var
  IS_CODESPACE=true
  DETECTED_NAME="$CODESPACE_NAME"
  echo "   Using CODESPACES environment variable"
else
  # Local development
  IS_CODESPACE=false
  echo "   Local development environment detected"
fi

if [ "$IS_CODESPACE" = "true" ]; then
  CODESPACE_URL_NEXT="https://${DETECTED_NAME}-3000.app.github.dev"
  CODESPACE_URL_TC="https://${DETECTED_NAME}-8080.app.github.dev"
  KC_HOSTNAME_VALUE="${DETECTED_NAME}-8080.app.github.dev"
else
  CODESPACE_URL_NEXT="http://localhost:3000"
  CODESPACE_URL_TC="http://localhost:8080"
  KC_HOSTNAME_VALUE="localhost:8080"
fi

echo "   Next.js URL: ${CODESPACE_URL_NEXT}"
echo "   TideCloak URL: ${CODESPACE_URL_TC}"
echo "   KC_HOSTNAME: ${KC_HOSTNAME_VALUE}"

echo "🔄 [2/3] Updating configuration files and environment..."
# Update tidecloak-demo-realm.json with Codespace URLs
sed -i "s|http://localhost:3000|${CODESPACE_URL_NEXT}|g" ./tidecloak-demo-realm.json
sed -i "s|https://[^/]*-3000\.app\.github\.dev|${CODESPACE_URL_NEXT}|g" ./tidecloak-demo-realm.json
sed -i "s|http://localhost:3000|${CODESPACE_URL_NEXT}|g" ./DevReadMe.md

# Create or update .env file with environment variables
if [ ! -f .env ]; then
  # If .env doesn't exist, copy from .env.overrides
  cp .env.overrides .env
fi

# Remove old BASE_URL and CUSTOM_URL entries if they exist
sed -i '/^BASE_URL=/d' .env
sed -i '/^CUSTOM_URL=/d' .env
sed -i '/# Codespace URLs/d' .env
sed -i '/# Local URLs/d' .env

# Write environment variables to .env file
if [ "$IS_CODESPACE" = "true" ]; then
  echo "Writing Codespace URLs to .env file..."
  echo "" >> .env
  echo "# Codespace URLs (auto-generated by startTC.sh)" >> .env
  echo "BASE_URL=${CODESPACE_URL_TC}" >> .env
  echo "CUSTOM_URL=${CODESPACE_URL_NEXT}" >> .env
else
  echo "Local environment detected, using localhost URLs..."
  echo "" >> .env
  echo "# Local URLs (auto-generated by startTC.sh)" >> .env
  echo "BASE_URL=http://localhost:8080" >> .env
  echo "CUSTOM_URL=http://localhost:3000" >> .env
fi

echo "🐳 [3/3] Pulling and starting Tidecloak container..."
if [ "$(docker ps -aq -f name=^tidecloak$)" ]; then
  docker rm tidecloak --force
fi
if [ ! -d "./Uploads" ]; then
  echo "Creating Uploads directory..."
  mkdir ./Uploads
else
  echo "Uploads directory already exists."
fi
if [ "$IS_CODESPACE" = "true" ]; then
  # Codespaces: Use full URL to avoid port in generated URLs
  echo "   Using KC_HOSTNAME_URL: ${CODESPACE_URL_TC}"
  docker run -d \
    --name tidecloak \
    -p 8080:8080 \
    -v .:/opt/keycloak/data/h2 \
    -v ./Uploads:/opt/keycloak/Uploads \
    -e KC_HOSTNAME_URL=${CODESPACE_URL_TC} \
    -e KC_HTTP_ENABLED=true \
    -e KC_BOOTSTRAP_ADMIN_USERNAME=admin \
    -e KC_BOOTSTRAP_ADMIN_PASSWORD=password \
    tideorg/tidecloak-dev:latest
else
  # Local: Use hostname with port
  docker run -d \
    --name tidecloak \
    -p 8080:8080 \
    -v .:/opt/keycloak/data/h2 \
    -v ./Uploads:/opt/keycloak/Uploads \
    -e KC_HOSTNAME=${KC_HOSTNAME_VALUE} \
    -e KC_HTTP_ENABLED=true \
    -e KC_BOOTSTRAP_ADMIN_USERNAME=admin \
    -e KC_BOOTSTRAP_ADMIN_PASSWORD=password \
    tideorg/tidecloak-dev:latest
fi

if [ -d ".next" ]; then
  echo "Removing previous .next directory..."
  sudo rm -rf .next
  if ! [ -d ".next" ]; then echo "Deleted!"; else echo "Failed to delete .next directory!"; fi
fi
# echo "{}" > data/tidecloak.json <-- Uncomment if you want to reset the Tidecloak data

echo ""
echo "⏳ Waiting for TideCloak to be ready..."
# Health check - wait for TideCloak to be accessible
MAX_RETRIES=30
RETRY_COUNT=0
while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
  if curl -sf "${CODESPACE_URL_TC}/health" > /dev/null 2>&1 || curl -sf "${CODESPACE_URL_TC}/" > /dev/null 2>&1; then
    echo "✅ TideCloak is ready!"
    break
  fi
  RETRY_COUNT=$((RETRY_COUNT + 1))
  if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
    echo "⚠️  Warning: TideCloak health check timed out after ${MAX_RETRIES} attempts."
    echo "   TideCloak may still be starting up. The app might experience connection issues."
  else
    echo "   Attempt $RETRY_COUNT/$MAX_RETRIES - waiting for TideCloak..."
    sleep 2
  fi
done

echo ""
echo "✅ Tidecloak Setup complete. You can close this terminal or continue below."
echo ""
